# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x17\n\x07NewUser\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x12\n\x10\x44ummyListRequest\".\n\x11\x44ummyListResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\",\n\rCreateReqeust\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.NewUser\"*\n\x0e\x43reateResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User2\x84\x01\n\x0bUserService\x12>\n\tDummyList\x12\x16.user.DummyListRequest\x1a\x17.user.DummyListResponse\"\x00\x12\x35\n\x06\x43reate\x12\x13.user.CreateReqeust\x1a\x14.user.CreateResponse\"\x00\x42\x30Z.github.com/hsmtkk/literate-barnacle/proto/userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/hsmtkk/literate-barnacle/proto/user'
  _NEWUSER._serialized_start=20
  _NEWUSER._serialized_end=43
  _USER._serialized_start=45
  _USER._serialized_end=77
  _DUMMYLISTREQUEST._serialized_start=79
  _DUMMYLISTREQUEST._serialized_end=97
  _DUMMYLISTRESPONSE._serialized_start=99
  _DUMMYLISTRESPONSE._serialized_end=145
  _CREATEREQEUST._serialized_start=147
  _CREATEREQEUST._serialized_end=191
  _CREATERESPONSE._serialized_start=193
  _CREATERESPONSE._serialized_end=235
  _USERSERVICE._serialized_start=238
  _USERSERVICE._serialized_end=370
# @@protoc_insertion_point(module_scope)
